### ISSUE TITLE
I cannot install the lv_font_conv script

### ISSUE THREAD

**Issue by seyyah** [littlevgl/lv_font_conv#12]
I used it before but I'm not very familiar nodejs, npm etc.

**Try 1**:

```sh
$ npm i lv_font_conv -g
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/lv_font_conv - Not found
npm ERR! 404 
npm ERR! 404  'lv_font_conv@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-07-04T09_48_47_767Z-debug.log
```

**Try 2**:

```sh
$ npm i littlevgl/lv_font_conv -g
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules'] {
npm ERR!   stack: "Error: EACCES: permission denied, access '/usr/local/lib/node_modules'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/seyyah/.npm/_logs/2019-07-04T09_50_17_836Z-debug.log
```

**Try 3**: 

Firstly I fix EACCESS issue,

```sh
sudo chown -R `whoami` ~/.npm
sudo chown -R `whoami` /usr/local/lib/node_modules
```

And then

```sh
$ npm i littlevgl/lv_font_conv -g
/usr/local/bin/lv_font_conv -> /usr/local/lib/node_modules/lv_font_conv/lv_font_conv.js

> canvas@2.5.0 install /usr/local/lib/node_modules/lv_font_conv/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
# <<< LONG TIME WAIT THIS LINE AND DO NOT CONTINUE >>>>
```

## Environment

```sh
$ nodejs -v
v10.16.0
$ npm -v
6.9.0
$ node -v
v12.5.0

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.10
Release:        18.10
Codename:       cosmic
```

## :clipboard: Reference
1. https://stackoverflow.com/questions/25290986/how-to-fix-eacces-issues-with-npm-install/29787931

**Comment by puzrin** [comment]
Comments:

**try 1**. I did not published package in npm yet. Hoped to see some feedback. Use second option - `npm i littlevgl/lv_font_conv -g`

**try 2**. NEVER use global node install. Cleanup all those files and use https://github.com/nvm-sh/nvm (follow instructions there)

**try 3**.

Just tested - works with 12.6.0. Try again, probably, temporary problem with remote site (or try via VPN). Need more details - it just hangs forever or shows some errors in the end?

**Comment by seyyah** [comment]
> Comments:
> 
> **try 1**. I did not published package in npm yet. Hoped to see some feedback. Use second option - `npm i littlevgl/lv_font_conv -g`

Ok
 
> **try 2**. NEVER use global node install.

According to [1], I try to install. I'm not professional on the node/npm etc.

> Cleanup all those files and use https://github.com/nvm-sh/nvm (follow instructions there)

Later, "try 3" worked properly. So I didn't try to this suggestion.
 
> **try 3**.
> 
> Just tested - works with 12.6.0. Try again, probably, temporary problem with remote site

You're right. After trying several times and waiting a long time, it recovered to itself.

Thanks @puzrin 

## :clipboard: Reference
1. https://github.com/littlevgl/lv_font_conv/blob/master/README.md#install-the-script

**Comment by puzrin** [comment]
close? any more questions?

**Comment by seyyah** [comment]
I installed successfully but I cannot run `lv_font_conv`. It produces error

```sh
$ npm i littlevgl/lv_font_conv

> canvas@2.5.0 install /home/seyyah/tmp/node/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
[canvas] Success: "/home/seyyah/tmp/node/node_modules/canvas/build/Release/canvas.node" is installed via remote
npm WARN saveError ENOENT: no such file or directory, open '/home/seyyah/tmp/node/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/seyyah/tmp/node/package.json'
npm WARN node No description
npm WARN node No repository field.
npm WARN node No README data
npm WARN node No license field.

+ lv_font_conv@0.1.0
added 83 packages from 59 contributors and audited 131 packages in 94.932s
found 0 vulnerabilities
```

When I try to run `lv_font_conv`, it produces error,

```sh
$ lv_font_conv 
/usr/local/lib/node_modules/lv_font_conv/lv_font_conv.js:17
  throw err;
  ^

Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- /usr/local/lib/node_modules/lv_font_conv/node_modules/canvas/lib/bindings.js
- /usr/local/lib/node_modules/lv_font_conv/node_modules/canvas/lib/canvas.js
- /usr/local/lib/node_modules/lv_font_conv/node_modules/canvas/index.js
- /usr/local/lib/node_modules/lv_font_conv/lib/cli.js
- /usr/local/lib/node_modules/lv_font_conv/lv_font_conv.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/lv_font_conv/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/lv_font_conv/node_modules/canvas/lib/bindings.js',
    '/usr/local/lib/node_modules/lv_font_conv/node_modules/canvas/lib/canvas.js',
    '/usr/local/lib/node_modules/lv_font_conv/node_modules/canvas/index.js',
    '/usr/local/lib/node_modules/lv_font_conv/lib/cli.js',
    '/usr/local/lib/node_modules/lv_font_conv/lv_font_conv.js'
  ]
}
```

I try to install canvas and i got an error

```sh
$ npm i canvas

> canvas@2.5.0 install /home/user/tmp/node/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
[canvas] Success: "/home/user/tmp/node/node_modules/canvas/build/Release/canvas.node" is installed via remote
npm WARN saveError ENOENT: no such file or directory, open '/home/user/tmp/node/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/user/tmp/node/package.json'
npm WARN node No description
npm WARN node No repository field.
npm WARN node No README data
npm WARN node No license field.

+ canvas@2.5.0
updated 1 package and audited 590 packages in 90.768s
found 0 vulnerabilities
```

I got this line: "ENOENT: no such file or directory, open '/home/user/tmp/node/package.json'"

```sh
$ ls -al /home/user/tmp/node/
toplam 36
drwxr-xr-x  3 user user  4096 Tem  4 18:33 .
drwxr-xr-x 18 user user  4096 Tem  4 18:12 ..
drwxr-xr-x 84 user user  4096 Tem  4 18:36 node_modules
-rw-r--r--  1 user user 22999 Tem  4 18:33 package-lock.json
```

I try to re-install node-canvas different way [1,2]. But the result has not changed.

## :clipboard: Reference
1. https://github.com/Automattic/node-canvas/wiki/Installation%3A-Ubuntu-and-other-Debian-based-systems
2. https://github.com/Automattic/node-canvas/issues/284

**Comment by puzrin** [comment]
You missed option `-g` on install. You should use "global" (in scope of node) package install, or clone repo and run `npm i` there.

**Comment by seyyah** [comment]
I successfully install `lv_font_conv` and I want to document my installation steps.

1. Cleanup old files

> > Cleanup all those files and use https://github.com/nvm-sh/nvm (follow instructions there)
> try 2. NEVER use global node install. Cleanup all those files

```sh
sudo rm -rf /usr/local/lib/node_modules
sudo rm -rf ~/tmp/node/node_modules
```

2. Install nvm

```sh
$ sudo apt-get install build-essential libssl-dev
$ curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
$ source ~/.bashrc
$ nvm --version
0.34.0

$ nvm install node
[...]
Now using node v12.6.0 (npm v6.9.0)
Creating default alias: default -> node (-> v12.6.0)

$ nvm use node
Now using node v12.6.0 (npm v6.9.0)

$ nvm run node --version
Running node v12.6.0 (npm v6.9.0)
v12.6.0
```

3. Install lv_font_conv

```sh
$ nvm run node --version
Running node v12.6.0 (npm v6.9.0)
v12.6.0

$ npm i littlevgl/lv_font_conv -g
$ lv_font_conv -v
0.0.1
```

Thanks your interest and time @puzrin and @kisvegabor 

## :clipboard: Reference
1. https://github.com/nvm-sh/nvm
